### ISSUE TITLE
Validator self-stake < 1024 after slashing, the validator can be unjailed and join the validator set

### ISSUE THREAD

**Issue by tyitang** [piplabs/story#258] opened 2024-10-20 05:57 UTC
## Description and context

Validator self-stake < 1024 after slashing, the validator can be unjailed and join the validator set

## Steps to reproduce

1. Create a validator with 1024 IPs
2. Delegator stake 5000 IPs to the validator
3. Validator offline and been jailed
4. After the jail duration, call unjail validator

## Experienced behavior

The validator joined the validator set after call unjail

## Expected behavior

The validator can't be unjailed since its self-stake is less than 1024 after slashing

**Comment by lucas2brh** [comment] 2024-10-21 09:29
https://github.com/storyprotocol/l1-tests/blob/update-slashing-test/tests/slashing.test.ts#L461

**Comment by 0xHansLee** [comment] 2024-10-24 22:19
Confirmed that it was due to misconfiguration, so close the issue.

**Closed by 0xHansLee** 2024-10-24 22:19 UTC
Labels: bug
