### ISSUE TITLE
Documentation Bug: Incorrect Flag for Validator Unstake Command in Story Odyssey CLI

### ISSUE THREAD

**Issue by Coha05** [piplabs/story#387] opened 2024-11-28 11:15 UTC
### Description and Context
There is a mismatch between the documentation and the CLI implementation of the validator unstake command for the Story Odyssey Validator. The documentation specifies the flag --unstake for unstaking tokens, but the actual CLI requires the use of --stake for specifying the amount to unstake in wei.

Documentation link: [Odyssey Validator Operations](https://docs.story.foundation/docs/odyssey-validator-operations#validator-unstaking)
### Steps to Reproduce
1. Refer to the documentation for unstaking tokens as a validator.
2. Use the provided command:
```bash
Copy code
./story validator unstake \
  --validator-pubkey ${VALIDATOR_PUB_KEY_IN_HEX} \
  --unstake ${AMOUNT_TO_UNSTAKE_IN_WEI}
```
3. Execute the command in the CLI.
### Experienced Behavior
- The CLI returns the error:
```
Fatal error occurred, app died unexpectedly !! err="unknown flag: --unstake"
```
- Upon using the `-h` flag for `validator unstake`, the correct flag is listed as `--stake`.
### Expected Behavior
The documentation should align with the CLI implementation, using the `--stake` flag for unstaking tokens as described in the CLI help command output.
### Solution Recommendation
Update the documentation to reflect the correct CLI usage:
```
./story validator unstake \
  --validator-pubkey ${VALIDATOR_PUB_KEY_IN_HEX} \
  --stake ${AMOUNT_TO_UNSTAKE_IN_WEI}
```
This ensures consistency between the documentation and the CLI, preventing confusion and errors for users.

**Comment by edisonz0718** [comment] 2024-11-30 19:01
The issue is addressed in this commits: https://github.com/piplabs/story/pull/368
We intend to use --unstake in this case

**Closed by edisonz0718** 2024-11-30 19:01 UTC
Labels: bug
