### ISSUE TITLE
[POTENTIAL] misbehavior call staking with large data

### ISSUE THREAD

**Issue by lucas2brh** [piplabs/story#288] opened 2024-10-23 16:39 UTC
## Description and context
 call staking operation with large data (127KB), wait 30s, wallet balance sometimes isn't updated, run multiple times, failed at different operations.

@[Staking-60-01](https://www.notion.so/storyprotocol/Staking-60-01-889afcb3e65547439e42c290c08e7bc6?pvs=24)

https://github.com/storyprotocol/l1-tests/blob/753faf239c1f7b3d66017ffa7e0ed19203ec9193/tests/stake/createValidator.test.ts#L2873

**Comment by 0xHansLee** [comment] 2024-10-23 21:00
I tested to stake IP token with the large data (127kb) in my local env, it has been processed immediately. So it might some kind of network issue.

BTW, the fee for tx with large data is imposed much compared to the one with small data.
Comparing 127kb vs. 0. Gas usage for 127kb was about 3.3M gas and 0kb was 50k gas. This implies that if the user send tx with large amount of extra data, our system impose a large fee proportional to the size of data.

**Comment by limengformal** [comment] 2024-10-24 18:07
Closing. It is by design. Higher gas will prevent large data input.

**Closed by limengformal** 2024-10-24 18:07 UTC
Labels: bug
